import { describe, it, expect } from "vitest";
import { handleSkillXpInfo } from "../tools/utils.js";
import { handleCalcItemsToLevel } from "../tools/utils.js";

// XP values as computed by this server's formula (may differ slightly from wiki).
// Generated by running: node -e "..." against src/tools/utils.ts XP_TABLE logic.
const KNOWN_XP: Record<number, number> = {
  1:  0,
  2:  83,
  10: 1_151,
  50: 101_314,
  70: 737_600,
  99: 13_034_431,
};

describe("skill_xp_info", () => {
  it("returns level and xp_to_next for a given current_xp", async () => {
    const res = await handleSkillXpInfo({ current_xp: 737_627 });
    const data = JSON.parse(res.content[0].text);
    expect(data.current_level).toBe(70);
    expect(data.next_level).toBe(71);
    expect(data.xp_to_next_level).toBeGreaterThan(0);
  });

  it("returns total xp required for a given level", async () => {
    for (const [level, xp] of Object.entries(KNOWN_XP)) {
      const res = await handleSkillXpInfo({ level: Number(level) });
      const data = JSON.parse(res.content[0].text);
      expect(data.xp_required).toBe(xp);
    }
  });

  it("returns 0 xp_to_next_level at max XP", async () => {
    // xpToLevel caps at 98 (loop runs 98→1), but next_level_xp = levelToXp(99) = 13_034_431
    // so xp_to_next = 13_034_431 - 13_034_431 = 0
    const res = await handleSkillXpInfo({ current_xp: 13_034_431 });
    const data = JSON.parse(res.content[0].text);
    expect(data.xp_to_next_level).toBe(0);
  });

  it("errors when neither level nor current_xp provided", async () => {
    const res = await handleSkillXpInfo({});
    expect(res.isError).toBe(true);
  });
});

describe("calc_items_to_level", () => {
  it("calculates magic logs to 99 FM from level 70", async () => {
    // 70→99 woodcutting at 87.5 XP/log
    const res = await handleCalcItemsToLevel({
      skill: "Firemaking",
      current_level: 70,
      target_level: 99,
      xp_per_item: 87.5,
    });
    const data = JSON.parse(res.content[0].text);
    expect(data.skill).toBe("Firemaking");
    expect(data.current_level).toBe(70);
    expect(data.current_xp).toBe(KNOWN_XP[70]);
    expect(data.target_xp).toBe(KNOWN_XP[99]);
    expect(data.xp_needed).toBe(KNOWN_XP[99]! - KNOWN_XP[70]!);
    expect(data.items_needed).toBe(Math.ceil((KNOWN_XP[99]! - KNOWN_XP[70]!) / 87.5));
  });

  it("accepts current_xp instead of current_level", async () => {
    const res = await handleCalcItemsToLevel({
      skill: "Woodcutting",
      current_xp: 0,
      target_level: 2,
      xp_per_item: 25,
    });
    const data = JSON.parse(res.content[0].text);
    // Level 2 requires 83 XP, starting from 0 → ceil(83/25) = 4 items
    expect(data.items_needed).toBe(4);
  });

  it("errors when target_level is not higher than current", async () => {
    const res = await handleCalcItemsToLevel({
      skill: "Mining",
      current_level: 70,
      target_level: 70,
      xp_per_item: 50,
    });
    expect(res.isError).toBe(true);
  });

  it("errors when neither current_level nor current_xp provided", async () => {
    const res = await handleCalcItemsToLevel({
      skill: "Mining",
      target_level: 99,
      xp_per_item: 50,
    });
    expect(res.isError).toBe(true);
  });
});
